name: Publish crate to crates.io
on:
  workflow_call:
    secrets:
      CRATES_IO_TOKEN:
        description: crates.io token
        required: true
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Publish lib to crates.io if it is not published
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          crate_name="ribboncurls"
          version="$(cargo read-manifest --manifest-path "./$crate_name/Cargo.toml" | jq -r ".version")"
          response=$(curl -s "https://crates.io/api/v1/crates/$crate_name")
          if ! echo "$response" | grep -q "\"num\":\"$version\""; then
            cargo publish -p "$crate_name" --locked
          fi

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish -p ribboncurls-cli --locked
