name: Setup Environment
on:
  workflow_call:
    outputs:
      git_tag_name:
        description: "Git release tag name"
        value: ${{ jobs.setup.outputs.git_tag_name }}
      cargo_cache_key:
        description: "Cargo cache key for the build"
        value: ${{ jobs.setup.outputs.cargo_cache_key }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.git_tag_name.outputs.value }}
      cargo_cache_key: ${{ steps.cargo_cache_key.outputs.value }}
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0

      - name: Set cargo cache key
        id: cargo_cache_key
        run: |
          CARGO_CACHE_KEY="${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          echo "value=$CARGO_CACHE_KEY" >> $GITHUB_OUTPUT

      - uses: actions/cache@81382a721fc89d96eca335d0c3ba33144b2baa9d # v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ steps.cargo_cache_key.outputs.value }}
          id: cache-cargo-release

      - name: Set git_tag_name from latest Cargo.toml version
        id: git_tag_name
        run: |
          VERSION=$(cargo read-manifest --manifest-path ./ribboncurls-cli/Cargo.toml | jq -r ".version")
          echo "value=v$VERSION" >> $GITHUB_OUTPUT

      - name: Ensure the release tag does not exist
        run: |
          version="${{ steps.git_tag_name.outputs.value }}"
          if git rev-parse "$version" >/dev/null 2>&1; then
            echo "This git tag already exists: $version"
            exit 1
          fi

      - name: Ensure crate version doesn't already exist
        run: |
          crate_name="ribboncurls-cli"
          version="${{ steps.git_tag_name.outputs.value }}"
          version=${version#v} # strip prefix 'v'
          response=$(curl -s "https://crates.io/api/v1/crates/$crate_name")
          if echo "$response" | grep -q "\"num\":\"$version\""; then
            echo "Version $version of $crate_name already exists."
            exit 1
          fi

      - name: Ensure changelog entry for version exists
        run: |
          version=$(cargo read-manifest --manifest-path ./ribboncurls-cli/Cargo.toml | jq -r ".version")
          if ! grep -q "## \[$version\]" ./ribboncurls-cli/CHANGELOG.md; then
            echo "Changelog doesn't contain an entry for this version: $version"
            exit 1
          fi
