name: Tag release
on:
  workflow_call:
    secrets:
      RELEASE:
        description: Token to add tag
        required: true
    inputs:
      git_tag_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      git_tag_name:
        description: Git version tag (eg. v0.3.0)
        required: true

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
        with:
          token: ${{ secrets.RELEASE }}

      - name: Add git tag to release
        run: |
          TAG_COMMIT_HASH=$(git rev-parse HEAD)
          git tag ${{ inputs.git_tag_name }} ${TAG_COMMIT_HASH}
          git push origin ${{ inputs.git_tag_name }}
